export const MOVIE_CREATE_REQUEST = "MOVIE_CREATE_REQUEST"
export const MOVIE_CREATE_SUCCESS = "MOVIE_CREATE_SUCCESS"
export const MOVIE_CREATE_FAIL = "MOVIE_CREATE_FAIL"
export const MOVIE_CREATE_RESET = "MOVIE_CREATE_RESET"

export const MOVIE_ALL_REQUEST = "MOVIE_ALL_REQUEST"
export const MOVIE_ALL_SUCCESS = "MOVIE_ALL_SUCCESS"
export const MOVIE_ALL_FAIL = "MOVIE_ALL_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"